# Generated by Django 2.1.7 on 2019-06-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='None')),
                ('Phone', models.TextField(default='None')),
                ('Email', models.TextField(default='None')),
            ],
        ),
    ]
